spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conexemi
    username: root
    password: ADMIN

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
