spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conexemi
    username: root
    password: 123456789

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
